package com.icinfo.platform.student.mapper;

import com.icinfo.platform.student.model.StuTable;

public interface StuTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_table
     *
     * @mbg.generated
     */
    int insert(StuTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_table
     *
     * @mbg.generated
     */
    int insertSelective(StuTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_table
     *
     * @mbg.generated
     */
    StuTable selectByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StuTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StuTable record);
}